### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by mhdGit402** [mhdGit402/Job-Listing#1]
- [x] 1- Navigation component and routing with default templates

- [x] 2- Create Home page

- [x]  3- Create Jobs page

- [x] 4- Add related functionality to Home and Jobs page

- [x] 5- Create Job page

- [x] 6- Create Add Job page and add related functionality

- [x] 7- Create Update page and add related functionality

- [x] 8- Add related functionality to delete job

-- issue

- [x] 1- active class for navigation menu (by using NavLink)

- [x] 2- fix manage job ui section in /jobs/:id page
